/* Run with: node scripts/verify_maren_ui.cjs /path/to/playwright */
const { chromium } = require(process.argv[2] || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const root = path.resolve(__dirname, '..');
  const data = JSON.parse(fs.readFileSync(path.join(root, 'data/scoring.json'), 'utf8'));
  const pageUrl = pathToFileURL(path.join(root, 'index.html')).href;
  const storageKey = `limineer-maren-answers-v1-${data.metadata.exported_at}`;
  const browser = await chromium.launch({channel: 'chrome', headless: true});
  const context = await browser.newContext({viewport: {width: 390, height: 844}, reducedMotion: 'reduce'});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto(pageUrl);
    assert.deepEqual(await page.locator('.site-item').evaluateAll(items => items.map(item => item.dataset.siteId)), ['S-003', 'S-018', 'S-017', 'S-027', 'S-014']);
    assert.deepEqual(await page.locator('.rank').allTextContents(), ['01', '01', '03', '04', '05']);
    assert.equal(await page.locator('#compare-toggle').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.locator('#comparison-guide').isVisible(), false);
    assert.equal(await page.locator('.score-comparison:visible').count(), 0);
    assert.equal(await page.locator('.comparison-unchanged:visible').count(), 0);
    assert.equal(await page.locator('.criterion:visible').count(), 0);
    assert.equal(await page.locator('.site-reason').count(), 0);
    assert.deepEqual(await page.locator('.decision-label').allTextContents(), ['Start site checks', 'Start site checks', 'Start site checks', 'Confirm local support', 'Secure owner intent']);
    assert.deepEqual(await page.locator('.fit-band strong').allTextContents(), Array(5).fill('High fit'));
    const washes = await page.locator('.site-item').evaluateAll(items => items.map(item => Number(item.style.getPropertyValue('--rank-wash'))));
    assert.equal(washes[0], washes[1], 'Tied leaders have equal visual emphasis');
    assert.ok(washes[1] > washes[2] && washes[2] > washes[3] && washes[3] > washes[4]);
    await page.screenshot({path: '/private/tmp/maren-mobile.png', fullPage: true});
    await page.screenshot({path: '/private/tmp/maren-mobile-first-screen.png'});
    const rationale = page.locator('.secondary-disclosure').filter({has: page.getByText('Why this shortlist is defensible', {exact: true})});
    await rationale.locator(':scope > summary').click();
    assert.equal(await rationale.locator('.rubric-row:visible').count(), 0, 'Defensibility leads with evidence rules, not calculation');
    assert.match(await rationale.locator('.method-content').textContent(), /Recorded evidence comes first/);
    await rationale.locator('.evidence-disclosure > summary').click();
    assert.equal(await rationale.locator('.rubric-row:visible').count(), 6, 'Weights require a further disclosure');
    await rationale.locator(':scope > summary').click();
    await page.locator('#detail-S-003 > summary').click();
    assert.equal(await page.locator('#detail-S-003 .aggregate-row:visible').count(), 3);
    assert.equal(await page.locator('#detail-S-003 .criterion:visible').count(), 0, 'Summary does not expose the full rubric');
    assert.equal(await page.locator('#detail-S-003 .aggregate-bar').count(), 0);
    assert.doesNotMatch(await page.locator('#detail-S-003 .aggregate-content').textContent(), /\d+\s*\/\s*\d+|\d+ points/);
    assert.deepEqual(await page.locator('#detail-S-003 .aggregate-explanation').allTextContents(), ['Strong capacity · nearby substation', 'Signed owner intent · local support recorded', 'Low flood risk · large parcel']);
    assert.deepEqual(await page.locator('#detail-S-003 .score-word-best').allTextContents(), ['Strong capacity', 'nearby substation', 'Signed owner intent', 'local support recorded', 'large parcel']);
    assert.equal(await page.locator('#detail-S-003 .score-word-good').textContent(), 'Low flood risk');
    await page.screenshot({path: '/private/tmp/maren-summary.png'});
    await page.locator('#detail-S-003 [data-open-breakdown]').click();
    assert.equal(await page.locator('#breakdown-dialog').evaluate(dialog => dialog.open), true);
    assert.equal(await page.locator('#breakdown-title').textContent(), 'Kessby Old Quarry Yard');
    assert.equal(await page.locator('#breakdown-dialog .criterion:visible').count(), 6);
    assert.equal(await page.locator('#site-list .criterion').count(), 0, 'Full breakdown is not in the shortlist');
    await page.screenshot({path: '/private/tmp/maren-breakdown-dialog.png'});
    await page.locator('#breakdown-dialog .evidence-disclosure > summary').click();
    assert.match(await page.locator('#breakdown-dialog blockquote').first().textContent(), /12% revenue share/);
    await page.locator('#close-breakdown').click();
    assert.equal(await page.locator('#breakdown-dialog').evaluate(dialog => dialog.open), false);
    assert.equal(await page.locator('#detail-S-003 [data-open-breakdown]').evaluate(button => button === document.activeElement), true, 'Close restores focus to opener');
    assert.equal(await page.locator('#detail-S-003').evaluate(detail => detail.open), true, 'Rank summary stays open');
    await page.locator('.assumption-bar [data-open-questions]').click();
    assert.equal(await page.locator('#questions-dialog').evaluate(dialog => dialog.open), true);
    await page.getByRole('radio', {name: /Explore vendor upside/}).check();
    assert.equal(await page.locator('.site-item').first().getAttribute('data-site-id'), 'S-007');
    assert.match(await page.locator('#question-impact').textContent(), /Tallow Cross Brownfield enters/);
    assert.match(await page.locator('#assumption-state').textContent(), /1 \/ 4 answered/);
    assert.equal(await page.locator('.site-item').first().locator('.decision-label').textContent(), 'Verify grid capacity');
    await page.locator('#next-question').click();
    await page.getByRole('radio', {name: /Explore confirmed support/}).check();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#questions-dialog').evaluate(dialog => dialog.open), false);
    await page.locator('#detail-S-027 > summary').click();
    assert.equal(await page.locator('#detail-S-027 .aggregate-explanation').nth(1).textContent(), 'Signed owner intent · support assumed');
    assert.equal(await page.locator('#detail-S-027 .aggregate-explanation').nth(1).locator('.score-word-best').textContent(), 'Signed owner intent');
    assert.equal(await page.locator('#detail-S-027 .aggregate-explanation').nth(1).locator('.score-word-caution').textContent(), 'support assumed');
    await page.reload();
    assert.equal(await page.locator('.site-item').first().getAttribute('data-site-id'), 'S-007');
    assert.match(await page.locator('#assumption-state').textContent(), /2 \/ 4 answered/);
    await page.locator('.assumption-bar [data-open-questions]').click();
    await page.locator('#reset-questions').click();
    assert.equal(await page.locator('.site-item').first().getAttribute('data-site-id'), 'S-003');
    assert.match(await page.locator('#assumption-state').textContent(), /Conservative defaults/);
    assert.equal(await page.getByRole('radio', {name: /Official figures/}).isChecked(), true);
    await page.keyboard.press('Escape');
    await page.locator('#detail-S-003 > summary').click();
    await page.locator('#compare-toggle').click();
    assert.equal(await page.locator('#comparison-guide').isVisible(), true);
    assert.equal(await page.locator('.score-comparison:visible').count(), 3);
    assert.equal(await page.locator('.comparison-unchanged:visible').count(), 2);
    assert.equal(await page.locator('[data-site-id="S-003"] .comparison-unchanged strong').textContent(), 'No change in recommendation');
    assert.equal(await page.locator('[data-site-id="S-003"] .comparison-context').textContent(), 'Now = Potential');
    assert.equal(await page.locator('[data-site-id="S-017"] .comparison-risky .comparison-label').textContent(), 'Shortlisted option');
    assert.match(await page.locator('[data-site-id="S-017"] .comparison-why').textContent(), /Other sites improve.*fit and required checks stay the same/);
    assert.equal(await page.locator('[data-site-id="S-027"] .comparison-state').count(), 2, 'Each comparison has a consistent Now and target pair');
    assert.deepEqual(await page.locator('[data-site-id="S-027"] .comparison-state-title').allTextContents(), ['Now', 'Potential']);
    assert.equal(await page.locator('[data-site-id="S-027"] .comparison-risky .comparison-label').textContent(), 'Leading choice');
    assert.match(await page.locator('[data-site-id="S-027"] .comparison-why').textContent(), /Confirmed local support.*noise-report/);
    assert.equal(await page.locator('[data-site-id="S-014"] .comparison-risky .comparison-label').textContent(), 'Backup option');
    assert.equal(await page.locator('#compare-toggle').getAttribute('aria-pressed'), 'true');
    await page.screenshot({path: '/private/tmp/maren-comparison.png', fullPage: true});
    await page.locator('.assumption-bar [data-open-questions]').click();
    await page.getByRole('radio', {name: /Explore vendor upside/}).check();
    assert.equal(await page.locator('[data-site-id="S-007"] .comparison-unchanged strong').textContent(), 'No change in recommendation', 'Selected grid assumptions already match the potential case');
    assert.equal(await page.locator('#questions-dialog').evaluate(dialog => dialog.open), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.score-comparison:visible').count(), 1, 'Comparison uses current answers rather than comparing all three profiles indiscriminately');
    assert.equal(await page.locator('.comparison-unchanged:visible').count(), 4);
    const beforeCompare = await page.locator('.site-item').evaluateAll(items => items.map(item => item.dataset.siteId));
    await page.locator('[data-compare-target="evidence"]').click();
    assert.deepEqual(await page.locator('.site-item').evaluateAll(items => items.map(item => item.dataset.siteId)), beforeCompare, 'Choosing a comparison never changes the current ranking');
    assert.equal(await page.locator('[data-site-id="S-007"] .comparison-base .comparison-label').textContent(), 'Backup option');
    assert.deepEqual(await page.locator('[data-site-id="S-007"] .comparison-fit').allTextContents(), ['High fit', 'Medium fit']);
    assert.match(await page.locator('[data-site-id="S-007"] .comparison-why').textContent(), /official grid capacity/);
    assert.match(await page.locator('#comparison-explanation').textContent(), /Now uses your selected assumptions/);
    await page.locator('[data-site-id="S-007"]').screenshot({path: '/private/tmp/maren-evidence-comparison.png'});
    await page.locator('[data-compare-target="potential"]').click();
    await page.locator('#compare-toggle').click();
    assert.equal(await page.locator('.score-comparison:visible').count(), 0);
    assert.equal(await page.locator('.comparison-unchanged:visible').count(), 0);

    await page.locator('#alternatives > summary').click();
    assert.equal(await page.locator('.alternative:visible').count(), 3, 'Outside list starts compact');
    await page.locator('.alternative > summary').first().click();
    assert.match(await page.locator('.alternative[open] .alternative-core').textContent(), /Stronger options|Equal priority/);
    assert.equal(await page.locator('.alternative .criterion').count(), 0, 'Outside list keeps the rubric in the dialog');
    await page.locator('#more-alternatives').click();
    assert.equal(await page.locator('.alternative:visible').count(), 6);
    await page.locator('[data-alternative-group="potential"]').click();
    assert.equal(await page.locator('.alternative:visible').count(), 3);
    assert.equal(await page.locator('.alternative-blocker:visible').count(), 3, 'Potential blockers are visible before opening');
    assert.match(await page.locator('#alternative-S-009 .alternative-blocker').textContent(), /reserve overlap/);
    await page.locator('#alternative-S-009 > summary').click();
    assert.match(await page.locator('#alternative-S-009 .alternative-core').first().textContent(), /legal clearance is unresolved/);
    assert.match(await page.locator('#alternative-S-009 .alternative-core').nth(1).textContent(), /official grid capacity/);
    await page.screenshot({path: '/private/tmp/maren-potential-browser.png', fullPage: true});
    await page.locator('#alternative-S-009 [data-open-breakdown]').click();
    assert.equal(await page.locator('#breakdown-title').textContent(), 'Esk Mill Land');
    await page.keyboard.press('Escape');
    await page.locator('[data-alternative-group="excluded"]').click();
    assert.equal(await page.locator('.alternative:visible').count(), 2);
    await page.locator('#alternative-S-020 > summary').click();
    assert.match(await page.locator('#alternative-S-020 .alternative-core').textContent(), /refusal/);
    await page.locator('#alternatives > summary').click();

    // The UI must respect every ranking, tie and admission decision in the scoring output.
    for (const profile of data.profiles) {
      await page.evaluate(({storageKey, answers}) => sessionStorage.setItem(storageKey, JSON.stringify(answers)), {storageKey, answers: profile.answers});
      await page.reload();
      const rendered = await page.locator('.site-item').evaluateAll(items => items.map(item => item.dataset.siteId));
      assert.deepEqual(rendered, profile.rankings.eligible.slice(0, 5), profile.id);
      const ranks = await page.locator('.rank').allTextContents();
      const expectedRanks = rendered.map(id => String(data.sites.find(site => site.site_id === id).scores[profile.id].rank).padStart(2, '0'));
      assert.deepEqual(ranks, expectedRanks, `${profile.id}: shared ranks`);
      const expectedWashes = rendered.map(id => {
        const score = data.sites.find(site => site.site_id === id).scores[profile.id];
        return Number((0.01 + 0.26 * Math.pow((5 - Math.min(score.rank, 5)) / 4, 1.25) * (0.7 + 0.3 * score.score / 100)).toFixed(4));
      });
      const actualWashes = await page.locator('.site-item').evaluateAll(items => items.map(item => Number(item.style.getPropertyValue('--rank-wash'))));
      assert.ok(actualWashes.every((wash, index) => Math.abs(wash - expectedWashes[index]) < 0.00011), `${profile.id}: gradient follows current rank and score within rounding precision`);
      assert.ok(actualWashes.every((wash, index) => index === 0 || wash <= actualWashes[index - 1]), `${profile.id}: colour emphasis follows ranking`);
      assert.ok(rendered.every(id => !profile.rankings.conditional.includes(id) && !profile.rankings.excluded.includes(id)), profile.id);
      assert.equal(await page.locator('.site-header .score-value').count(), 0, `${profile.id}: scores remain a detail`);
      assert.equal(await page.locator('.site-header .decision-label').count(), 5);
      assert.deepEqual(await page.locator('.fit-band strong').allTextContents(), rendered.map(id => {
        const value = data.sites.find(site => site.site_id === id).scores[profile.id].score;
        return value >= 80 ? 'High fit' : value >= 60 ? 'Medium fit' : 'Low fit';
      }), `${profile.id}: fit bands follow the current score`);
      assert.doesNotMatch(await page.locator('#site-list').textContent(), /\d+\s*\/\s*100|[+±]\d+|\d+ points/, `${profile.id}: no numeric score or point changes in the decision layers`);
      for (const id of rendered) {
        const item = page.locator(`[data-site-id="${id}"]`);
        assert.equal(await item.locator('.score-comparison, .comparison-unchanged').count(), 1, `${profile.id}: every site explains its scenario status`);
      }
      await page.locator('.site-details > summary').first().click();
      await page.locator('.site-item [data-open-breakdown]').first().click();
      const firstScore = data.sites.find(site => site.site_id === rendered[0]).scores[profile.id].score;
      assert.equal(await page.locator('#breakdown-dialog .score-totals span').nth(2).textContent(), String(firstScore), `${profile.id}: exact current score remains available for audit`);
      await page.keyboard.press('Escape');
    }
    await page.setViewportSize({width: 1280, height: 1000});
    await page.locator('#reset-main').click();
    assert.deepEqual(await page.locator('.site-item').evaluateAll(items => items.map(item => item.dataset.siteId)), ['S-003', 'S-018', 'S-017', 'S-027', 'S-014']);
    await page.reload();
    await page.screenshot({path: '/private/tmp/maren-desktop.png', fullPage: true});
    await page.locator('#detail-S-003 > summary').click();
    const groupTops = await page.locator('#detail-S-003 .aggregate-row').evaluateAll(rows => rows.map(row => row.getBoundingClientRect().top));
    assert.ok(groupTops.every(top => Math.abs(top - groupTops[0]) < 1), 'Desktop evidence groups use the available width');
    await page.screenshot({path: '/private/tmp/maren-desktop-summary.png'});
    await page.locator('#detail-S-003 > summary').click();
    for (const width of [320, 375, 390, 768, 1280]) {
      await page.setViewportSize({width, height: 844});
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No overflow at ${width}px`);
      await page.locator('#compare-toggle').click();
      await page.locator('#detail-S-003 > summary').click();
      await page.locator('#detail-S-003 [data-open-breakdown]').click();
      assert.ok(await page.locator('#breakdown-dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth), `No breakdown overflow at ${width}px`);
      await page.keyboard.press('Escape');
      assert.equal(await page.locator('#breakdown-dialog').evaluate(dialog => dialog.open), false);
      await page.locator('#detail-S-003 > summary').click();
      await page.locator('#compare-toggle').click();
      await page.locator('.assumption-bar [data-open-questions]').click();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `No dialog overflow at ${width}px`);
      await page.keyboard.press('Escape');
    }
    assert.deepEqual(errors, [], 'No browser errors');
    console.log('Passed: breakdown dialog, evidence, dismissal and focus restoration; all 24 profiles, comparisons, aggregate disclosure, live answers, and 320–1280px layouts.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
